version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    reviewers:
      - 'Pagnet/fronts'
    assignees:
      - 'SauloSilva'
    versioning-strategy: increase
    commit-message:
      prefix: 'chore'
