name: CD

on:
  push:
    branches:
      - master
      - next
      - create-release-process # TODO: remove before merge

env:
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CI: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # We need to fetch all tags and branches
          fetch-depth: 0

      - name: Use Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: https://registry.npmjs.org/

      - name: Authenticate with Registry
        run: npm whoami

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build all
        run: yarn build

      - name: Creates a CANARY release and publishes if necessary
        if: github.ref == 'refs/heads/create-release-process'
        run: npx lerna publish --canary --no-git-tag-version --no-changelog --preid beta --dist-tag beta --pre-dist-tag beta

      - name: Creates a CANARY release and publishes if necessary
        if: github.ref == 'refs/heads/next'
        run: npx lerna publish --canary --no-git-tag-version --no-changelog

      - name: Creates a STABLE release and publishes if necessary
        if: github.ref == 'refs/heads/master'
        run: npx lerna publish --conventional-graduate
